version: '3.8'

services:
  okx-sentry:
    build: .
    container_name: okx-sentry
    restart: unless-stopped
    depends_on:
      # 等待 redis 和 mysql 服务进入健康状态
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ./configs:/root/configs
      - ./log:/root/log
    environment:
      - TZ=Asia/Shanghai
    networks:
      - okx-network
    # 健康检查
    healthcheck:
      test: ["CMD", "pgrep", "-f", "okx-sentry"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  redis:
    image: redis:7-alpine
    container_name: okx-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - okx-network

  mysql:
    image: mysql:8.0
    container_name: okx-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: okx123456
      MYSQL_DATABASE: okx_strategy
      MYSQL_USER: okx_user
      MYSQL_PASSWORD: okx123456
      TZ: Asia/Shanghai
      # 启用慢查询日志
      MYSQL_INITDB_ARGS: "--slow-query-log=1 --slow-query-log-file=/var/log/mysql/slow.log --long-query-time=2"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --innodb-buffer-pool-size=256M
      --max-connections=100
      --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pokx123456"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - okx-network

volumes:
  redis_data:
    driver: local
  mysql_data:
    driver: local
  mysql_logs:
    driver: local

networks:
  okx-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16