version: '3.8'

services:
  okx-sentry:
    build: .
    container_name: okx-market-sentry
    restart: unless-stopped
    environment:
      - DINGTALK_WEBHOOK_URL=${DINGTALK_WEBHOOK_URL}
      - REDIS_URL=redis:6379
      - LOG_LEVEL=info
    depends_on:
      - redis
    volumes:
      - ./logs:/root/logs
    networks:
      - okx-network

  redis:
    image: redis:7-alpine
    container_name: okx-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - okx-network

volumes:
  redis_data:

networks:
  okx-network:
    driver: bridge