log_level: info

redis:
  url: localhost:6379
  password:
  db: 0

dingtalk:
  webhook_url:   # 钉钉机器人 Webhook URL
  secret:        # 钉钉机器人加签密钥 (SEC开头的字符串)

alert:
  threshold: 3.0  # 预警阈值百分比

fetch:
  interval: 1m  # 数据获取间隔

pushplus:
  user_token:   # PushPlus用户令牌，用于微信推送通知
  to:           # 好友令牌，给朋友发送通知。多人用逗号分隔，如: "token1,token2"

network:
  proxy:        # HTTP代理地址，如需要请填写: http://127.0.0.1:7890
  timeout: 30s  # 网络请求超时时间