log_level: info

redis:
  url: localhost:6379
  password:
  db: 0

dingtalk:
  webhook_url:   # 钉钉机器人 Webhook URL (兼容保留)

alert:
  threshold: 3.0  # 预警阈值百分比

fetch:
  interval: 1m  # 数据获取间隔

pushplus:
  user_token:   # PushPlus用户令牌，用于微信推送通知
  to:           # 好友令牌，给朋友发送通知。多人用逗号分隔，如: "token1,token2"