log:
  level: debug # 日志级别 (debug, info, warn, error)
  file_path: log # 日志输出路径名
  # 日志文件大小 单位：MB，超限后会自动切割
  max_size: 200
  # 日志文件存放时间 单位：天
  max_age: 30
  # 日志文件备份数量
  max_backups: 7
  # 日志文件压缩
  compress: false

redis:
  url: redis:6379
  password:
  db: 0

dingtalk:
  webhook_url:   # 钉钉机器人 Webhook URL
  secret:        # 钉钉机器人加签密钥 (SEC开头的字符串)

alert:
  threshold: 3.0       # 预警阈值百分比
  monitor_period: 10m   # 监控周期，支持格式: 1m, 5m, 10m, 1h 等

fetch:
  interval: 1m  # 数据获取间隔

pushplus:
  user_token:   # PushPlus用户令牌，用于微信推送通知
  to:           # 好友令牌，给朋友发送通知。多人用逗号分隔，如: "token1,token2"

network:
  proxy:        # HTTP代理地址，如需要请填写: http://127.0.0.1:7890
  timeout: 30s  # 网络请求超时时间

# 唐奇安通道策略配置
strategy:
  donchian:
    enabled: true                      # 是否启用唐奇安通道策略
    symbols: ["BTC-USDT", "ETH-USDT", "SOL-USDT"]  # 监控的交易对列表
    interval: 15m                    # K线周期，支持: 1m, 3m, 5m, 15m, 30m, 1H, 2H, 4H, 6H, 12H, 1D
    donchian_length: 30                # 唐奇安通道长度，计算最近N根K线的最高/最低价
    donchian_offset: 1                 # 唐奇安通道偏移，1表示不包含当前K线
    atr_length: 14                     # ATR指标长度，计算平均真实波幅的周期数
    consolidation_bars: 45             # 盘整检测K线数，判断盘整状态需要的最小K线数量
    volume_multiplier: 3.0             # 成交量倍数，突破时成交量必须是前一根K线的倍数
    min_signal_strength: 0.7           # 最小信号强度，0-1之间，过滤弱信号

# 数据库配置
database:
  mysql:
    host: mysql                        # MySQL服务器地址（Docker容器内使用服务名）
    port: 3306                         # MySQL端口
    username: root                     # 数据库用户名
    password: "okx123456"              # 数据库密码
    database: okx_strategy             # 数据库名称
    max_idle_conns: 10                 # 最大空闲连接数
    max_open_conns: 100                # 最大打开连接数

# WebSocket配置
websocket:
  okx_endpoint: "wss://ws.okx.com:8443/ws/v5/public"  # OKX WebSocket公共频道地址
  reconnect_interval: 5s             # 重连间隔时间
  ping_interval: 20s                 # 心跳间隔时间
  max_reconnect_attempts: 10         # 最大重连尝试次数